### ISSUE TITLE
Step 2.5 Blob IO functions

### ISSUE THREAD

**Issue by navjotk** [devitocodes/daks#7]
Write python functions of the following format:

- `def write_shot(shot_number, data)`
- `def read_shot(shot_number): return data`

where shot_number is an int and data is a Numpy array. These functions should write to (and read from) azure blob storage from the Kubernetes cluster (from inside the Devito docker image).

**Comment by georgeAccnt-GH** [comment]
@navjotk, you mean functions that use these under the hood?
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python
https://docs.microsoft.com/en-us/azure/machine-learning/team-data-science-process/explore-data-blob

I also use azcopy for large files.

**Comment by navjotk** [comment]
I have written in-memory versions of these functions now - uploading to this repo shortly.

**Comment by philippwitte** [comment]
Sorry, just saw this. I wrote functions like this for our serverless workflow. If you want, you should be able to recycle these. `array_put` and `array_get` are for writing and reading numpy arrays to blob. I also wrote some segy io functions, but it's more of a hack, since you copy the files to the local disk first and then read them using the segyio python package. Anyway, might be useful.

**Comment by philippwitte** [comment]
It's in our public repo: https://github.com/slimgroup/Azure2019/blob/master/src/AzureBatch/docker/tti_image/tti/AzureUtilities.py

**Comment by navjotk** [comment]
As I said, this is now done and also available on this repo (`azureio.py`)
